package xyz.fortern.minehunt.storage

import org.intellij.lang.annotations.Language
import java.util.logging.Logger
import javax.sql.DataSource

class PostgresStorage(
    dataSource: DataSource,
    logger: Logger,
) : SqlStorageAdapter(dataSource, logger) {
    override val schemaStatements = listOf(
        CREATE_GAME_RECORD,
        CREATE_MODE_INDEX,
        CREATE_FINISH_TYPE_INDEX,
        CREATE_DURATION_INDEX,
        CREATE_START_TIME_INDEX,
        CREATE_MINEHUNT_RECORD,
        CREATE_PLAYER_IN_GAME,
        CREATE_GAME_ID_RANK_INDEX,
        CREATE_PLAYER_UUID_RANK_INDEX,
        CREATE_RANK_INDEX,
    )

    companion object {
        @Language("SQL")
        private const val CREATE_GAME_RECORD = """
            CREATE TABLE IF NOT EXISTS game_record (
                id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uuid           VARCHAR(36) NOT NULL UNIQUE,
                mode           VARCHAR(32) NOT NULL,
                start_time     BIGINT      NOT NULL,
                end_time       BIGINT      NOT NULL,
                duration       BIGINT      NOT NULL,
                finish_type    VARCHAR(32) NOT NULL,
                overworld_seed BIGINT      NOT NULL,
                seeds          TEXT        NOT NULL,
                result         TEXT        NOT NULL
            )
        """

        private const val CREATE_MODE_INDEX =
            "CREATE INDEX IF NOT EXISTS game_record_mode_idx ON game_record (mode)"
        private const val CREATE_FINISH_TYPE_INDEX =
            "CREATE INDEX IF NOT EXISTS game_record_finish_type_idx ON game_record (finish_type)"
        private const val CREATE_DURATION_INDEX =
            "CREATE INDEX IF NOT EXISTS game_record_duration_idx ON game_record (duration)"
        private const val CREATE_START_TIME_INDEX =
            "CREATE INDEX IF NOT EXISTS game_record_start_time_idx ON game_record (start_time)"

        @Language("SQL")
        private const val CREATE_MINEHUNT_RECORD = """
            CREATE TABLE IF NOT EXISTS minehunt_record (
                game_id                 INTEGER PRIMARY KEY REFERENCES game_record (id)
                                            ON DELETE CASCADE ON UPDATE CASCADE,
                first_time_to_nether    BIGINT,
                first_time_to_the_end   BIGINT,
                first_player_to_nether  VARCHAR(36),
                first_player_to_the_end VARCHAR(36)
            )
        """

        @Language("SQL")
        private const val CREATE_PLAYER_IN_GAME = """
            CREATE TABLE IF NOT EXISTS player_in_game (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                game_id     INTEGER     NOT NULL REFERENCES game_record (id)
                                         ON DELETE CASCADE ON UPDATE CASCADE,
                player_uuid VARCHAR(36) NOT NULL,
                player_rank INTEGER     NOT NULL,
                details     TEXT        NOT NULL
            )
        """

        private const val CREATE_GAME_ID_RANK_INDEX =
            "CREATE INDEX IF NOT EXISTS player_in_game_game_rank_idx ON player_in_game (game_id, player_rank)"
        private const val CREATE_PLAYER_UUID_RANK_INDEX =
            "CREATE INDEX IF NOT EXISTS player_in_game_player_rank_idx ON player_in_game (player_uuid, player_rank)"
        private const val CREATE_RANK_INDEX =
            "CREATE INDEX IF NOT EXISTS player_in_game_rank_idx ON player_in_game (player_rank)"
    }
}
