name: Minehunt
version: '1.0-SNAPSHOT'
main: xyz.fortern.minehunt.Minehunt
api-version: '1.21'
authors: [ Fortern ]

# TODO 插件加载时机

commands:
  test:
    description: "测试"
  minehunt:
    description: "游戏主命令"
    aliases: [mh]
