package xyz.fortern.minehunt.storage

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.lang.reflect.Proxy
import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import java.util.logging.Logger
import javax.sql.DataSource

class SqlStorageSchemaTest {
    @Test
    fun `mysql schema uses mysql identities indexes and player rank column`() {
        val executed = mutableListOf<String>()
        val storage = MysqlStorage(recordingDataSource(executed), Logger.getLogger("MysqlStorageSchemaTest"))

        storage.prepareSchema()

        assertEquals(4, executed.size)
        val schema = executed.joinToString("\n")
        assertTrue(schema.contains("AUTO_INCREMENT"))
        assertTrue(schema.contains("ENGINE = InnoDB"))
        assertTrue(schema.contains("player_rank"))
        assertTrue(schema.contains("KEY game_record_mode_idx"))
        assertTrue(schema.contains("bingo_record"))
        assertTrue(schema.contains("ON DELETE CASCADE ON UPDATE CASCADE"))
        assertTrue(executed.all { it.contains("CREATE TABLE IF NOT EXISTS") })
    }

    @Test
    fun `postgres schema uses identities idempotent indexes and player rank column`() {
        val executed = mutableListOf<String>()
        val storage = PostgresStorage(recordingDataSource(executed), Logger.getLogger("PostgresStorageSchemaTest"))

        storage.prepareSchema()

        assertEquals(4, executed.size)
        val schema = executed.joinToString("\n")
        assertTrue(schema.contains("GENERATED BY DEFAULT AS IDENTITY"))
        assertTrue(schema.contains("player_rank"))
        assertTrue(schema.contains("CREATE INDEX IF NOT EXISTS"))
        assertTrue(schema.contains("bingo_record"))
        assertTrue(schema.contains("ON DELETE CASCADE ON UPDATE CASCADE"))
        assertTrue(executed.filter { it.startsWith("CREATE TABLE") }.all { it.contains("IF NOT EXISTS") })
        assertTrue(executed.filter { it.startsWith("CREATE INDEX") }.all { it.contains("IF NOT EXISTS") })
    }

    private fun recordingDataSource(executed: MutableList<String>): DataSource {
        val statement = Proxy.newProxyInstance(
            javaClass.classLoader,
            arrayOf(Statement::class.java),
        ) { _, method, arguments ->
            when (method.name) {
                "executeUpdate" -> {
                    executed += arguments!![0] as String
                    0
                }

                "close" -> null
                "isClosed" -> false
                "isWrapperFor" -> false
                "unwrap" -> throw SQLException("Not a wrapper")
                else -> throw UnsupportedOperationException("Statement.${method.name}")
            }
        } as Statement
        val connection = Proxy.newProxyInstance(
            javaClass.classLoader,
            arrayOf(Connection::class.java),
        ) { _, method, _ ->
            when (method.name) {
                "createStatement" -> statement
                "close" -> null
                "isClosed" -> false
                "isWrapperFor" -> false
                "unwrap" -> throw SQLException("Not a wrapper")
                else -> throw UnsupportedOperationException("Connection.${method.name}")
            }
        } as Connection
        return Proxy.newProxyInstance(
            javaClass.classLoader,
            arrayOf(DataSource::class.java),
        ) { _, method, _ ->
            when (method.name) {
                "getConnection" -> connection
                "getLoginTimeout" -> 0
                "getLogWriter" -> null
                "getParentLogger" -> Logger.getLogger("RecordingDataSource")
                "setLoginTimeout", "setLogWriter" -> null
                "isWrapperFor" -> false
                "unwrap" -> throw SQLException("Not a wrapper")
                else -> throw UnsupportedOperationException("DataSource.${method.name}")
            }
        } as DataSource
    }
}
